version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
      eslint:
        patterns:
          - eslint*
          - '@eslint/*'
          - typescript-eslint

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
