// This file is generated by tools/sync-chart-adapter.mjs.
// Edit the shared adapter source in src/adapters instead.

// ============================================================================
// RiskLab Charts - Solid Adapter
// Native SolidJS integration for reactive charts.
// ============================================================================

import { createEffect, createMemo, createSignal, onCleanup, onMount } from 'solid-js';
import { Engine } from '@risklab/charts';
import { SyncController } from '@risklab/charts';
import { registry } from '@risklab/charts';
import { defaultTheme } from '@risklab/charts';
import type {
  ChartConfig,
  SeriesConfig,
  ThemeConfig,
  DataPoint,
  ChartEventType,
  ChartEventHandler,
} from '@risklab/charts';
import type { SyncOptions } from '@risklab/charts';

type MaybeAccessor<T> = T | (() => T);

function resolveAccessor<T>(value: MaybeAccessor<T>): T {
  if (typeof value === 'function') {
    return (value as () => T)();
  }
  return value;
}

export type SolidChartOptions = Omit<ChartConfig, 'container'>;

export interface SolidChartRef {
  engine: Engine | null;
  destroy(): void;
  update(config: Partial<ChartConfig>): void;
  setData(series: SeriesConfig[]): void;
  addSeries(series: SeriesConfig): void;
  removeSeries(id: string): void;
  toggleSeries(id: string): void;
  setTheme(theme: string | ThemeConfig): void;
  addPoint(seriesId: string, point: DataPoint, opts?: { shift?: boolean; maxPoints?: number }): void;
  exportChart(format?: 'png' | 'svg' | 'jpeg'): Promise<Blob | string>;
  on<T extends ChartEventType>(type: T, handler: ChartEventHandler<T>): () => void;
}

export function createSolidChart(el: HTMLElement, config: ChartConfig): SolidChartRef {
  let engine: Engine | null = new Engine({ ...config, container: el });

  return {
    get engine() {
      return engine;
    },
    destroy() {
      engine?.destroy();
      engine = null;
    },
    update(nextConfig) {
      engine?.update(nextConfig);
    },
    setData(series) {
      engine?.setData(series);
    },
    addSeries(series) {
      engine?.addSeries(series);
    },
    removeSeries(id) {
      engine?.removeSeries(id);
    },
    toggleSeries(id) {
      engine?.toggleSeries(id);
    },
    setTheme(theme) {
      engine?.setTheme(theme);
    },
    addPoint(seriesId, point, opts) {
      engine?.addPoint(seriesId, point, opts);
    },
    async exportChart(format = 'png') {
      if (!engine) throw new Error('Chart destroyed');
      return engine.export(format);
    },
    on(type, handler) {
      return engine?.on(type, handler) ?? (() => {});
    },
  };
}

export interface SolidChartReturn {
  container: () => HTMLElement | null;
  setContainer: (el: HTMLElement | null) => void;
  engine: () => Engine | null;
  update: (config: Partial<ChartConfig>) => void;
  setData: (series: SeriesConfig[]) => void;
  addSeries: (series: SeriesConfig) => void;
  removeSeries: (id: string) => void;
  toggleSeries: (id: string) => void;
  setTheme: (theme: string | ThemeConfig) => void;
  addPoint: (seriesId: string, point: DataPoint, opts?: { shift?: boolean; maxPoints?: number }) => void;
  exportChart: (format?: 'png' | 'svg' | 'jpeg') => Promise<Blob | string>;
  on: <T extends ChartEventType>(type: T, handler: ChartEventHandler<T>) => () => void;
  isMounted: () => boolean;
}

export function useChart(options: MaybeAccessor<SolidChartOptions>): SolidChartReturn {
  const [container, setContainer] = createSignal<HTMLElement | null>(null);
  const [engine, setEngine] = createSignal<Engine | null>(null);

  onMount(() => {
    const host = container();
    if (!host) return;
    const initial = resolveAccessor(options);
    setEngine(new Engine({ ...initial, container: host }));
  });

  onCleanup(() => {
    engine()?.destroy();
    setEngine(null);
  });

  createEffect(() => {
    const instance = engine();
    if (!instance) return;
    const next = resolveAccessor(options);
    instance.update(next);
  });

  const isMounted = createMemo(() => engine() !== null);

  return {
    container,
    setContainer,
    engine,
    update: (config) => engine()?.update(config),
    setData: (series) => engine()?.setData(series),
    addSeries: (series) => engine()?.addSeries(series),
    removeSeries: (id) => engine()?.removeSeries(id),
    toggleSeries: (id) => engine()?.toggleSeries(id),
    setTheme: (theme) => engine()?.setTheme(theme),
    addPoint: (seriesId, point, opts) => engine()?.addPoint(seriesId, point, opts),
    exportChart: async (format = 'png') => {
      const instance = engine();
      if (!instance) throw new Error('Chart not mounted');
      return instance.export(format);
    },
    on: (type, handler) => engine()?.on(type, handler) ?? (() => {}),
    isMounted,
  };
}

export function useTheme(initial: string | ThemeConfig = 'default') {
  const initialTheme =
    typeof initial === 'string' ? (registry.getTheme(initial) ?? defaultTheme) : initial;
  const [theme, setThemeSignal] = createSignal<ThemeConfig>(initialTheme);
  const [themeName, setThemeName] = createSignal<string>(
    typeof initial === 'string' ? initial : (initialTheme.id ?? 'custom'),
  );

  const setTheme = (next: string | ThemeConfig) => {
    const resolved = typeof next === 'string' ? (registry.getTheme(next) ?? defaultTheme) : next;
    setThemeSignal(resolved);
    setThemeName(typeof next === 'string' ? next : (resolved.id ?? 'custom'));
  };

  return { theme, themeName, setTheme };
}

export function useSync(options?: SyncOptions) {
  const [controller, setController] = createSignal<SyncController | null>(null);

  onMount(() => {
    setController(new SyncController(options ?? {}));
  });

  onCleanup(() => {
    controller()?.destroy();
    setController(null);
  });

  return {
    controller,
    syncEngine: (engine: Engine | null) => {
      if (engine) controller()?.add(engine);
    },
  };
}

export { Engine, SyncController };
export type { SyncOptions };
