export const ADVANCED_CHART_TYPES = [
  'polar',
  'polarArea',
  'smith',
  'contour',
  'vectorField',
  'altimeter',
  'attitudeIndicator',
  'compassRose',
  'spectrumAnalyzer',
  'oscilloscope',
  'networkTopology',
  'networkGraph',
  'flameChart',
  'windRose',
  'stripChart',
  'errorBand',
  'horizonChart',
  'bullet',
  'bulletChart',
  'sparkline',
  'sparklineChart',
  'violin',
  'sunburst',
  'sunburstChart',
  'chord',
  'chordDiagram',
] as const;

export type AdvancedChartType = typeof ADVANCED_CHART_TYPES[number];
