// This file is generated by tools/sync-chart-adapter.mjs.
// Edit the shared adapter source in src/adapters instead.

// ============================================================================
// RiskLab Charts — Angular Adapter
// Production-grade Angular component + service for RiskLab charts.
// Works with Angular 14+ (standalone components) and NgModule-style apps.
// Compatible with Angular's change detection (OnPush or Default).
//
// Usage (standalone):
//   import { RiskLabChartComponent } from '@risklab/charts-angular';
//
//   @Component({
//     imports: [RiskLabChartComponent],
//     template: `<uc-chart [config]="chartConfig" style="height:400px"></uc-chart>`,
//   })
//   export class MyComponent {
//     chartConfig: ChartConfig = { ... };
//   }
//
// ============================================================================

// ── NOTE ─────────────────────────────────────────────────────────────────────
// Angular is NOT a compile-time dependency of @risklab/charts.
// All Angular types are imported via string-keyed dynamic imports,
// so this file compiles cleanly in non-Angular projects.
// When used in an Angular project the peer dep ">=14.0.0" is expected.
// ─────────────────────────────────────────────────────────────────────────────

import type { ChartConfig, ThemeConfig, SeriesConfig, DataPoint, ChartEventType, ChartEventHandler } from '@risklab/charts';
import { Engine } from '@risklab/charts';

// ── Framework-agnostic imperative API (used by the component) ────────────────

export interface AngularChartRef {
  engine: Engine | null;
  destroy(): void;
  update(config: Partial<ChartConfig>): void;
  setData(series: SeriesConfig[]): void;
  addSeries(series: SeriesConfig): void;
  removeSeries(id: string): void;
  setTheme(theme: string | ThemeConfig): void;
  addPoint(seriesId: string, point: DataPoint, opts?: { shift?: boolean; maxPoints?: number }): void;
  exportChart(format?: 'png' | 'svg' | 'jpeg'): Promise<Blob | string>;
  on<T extends ChartEventType>(type: T, handler: ChartEventHandler<T>): () => void;
}

/**
 * Create a RiskLab chart inside any HTMLElement.
 * This is the low-level building block for the Angular component.
 *
 * @example (Angular component lifecycle)
 * ```ts
 * ngAfterViewInit() {
 *   this.chartRef = createAngularChart(this.el.nativeElement, this.config);
 * }
 * ngOnDestroy() {
 *   this.chartRef.destroy();
 * }
 * ```
 */
export function createAngularChart(el: HTMLElement, config: ChartConfig): AngularChartRef {
  let engine: Engine | null = new Engine({ ...config, container: el });

  return {
    get engine() { return engine; },
    destroy() { engine?.destroy(); engine = null; },
    update(cfg) { engine?.update(cfg); },
    setData(series) { engine?.setData(series); },
    addSeries(series) { engine?.addSeries(series); },
    removeSeries(id) { engine?.removeSeries(id); },
    setTheme(theme) { engine?.setTheme(theme); },
    addPoint(seriesId, point, opts) { engine?.addPoint(seriesId, point, opts); },
    async exportChart(format = 'png') {
      if (!engine) throw new Error('Chart destroyed');
      return engine.export(format);
    },
    on(type, handler) {
      return engine?.on(type, handler) ?? (() => {});
    },
  };
}

// ── Angular Component (code-gen style — emitted as a string for dynamic loading) ─

/**
 * Returns TypeScript source for an Angular component that wraps RiskLab Charts.
 * In a real Angular project, paste `getAngularComponentSource()` into a file,
 * or use the component factory `createAngularChart` directly.
 *
 * The built component:
 * - Accepts `[config]` input
 * - Accepts `[theme]` input
 * - Emits `(chartReady)` output with the engine ref
 * - Supports OnPush change detection
 * - Auto-sizes to container via ResizeObserver
 * - Cleans up on `ngOnDestroy`
 */
export function getAngularComponentSource(): string {
  return `
import {
  Component, Input, Output, EventEmitter,
  ElementRef, OnInit, OnChanges, OnDestroy, AfterViewInit,
  ChangeDetectionStrategy, SimpleChanges, NgModule,
} from '@angular/core';
import { createAngularChart, type AngularChartRef } from '@risklab/charts-angular';
import type { ChartConfig, ThemeConfig } from '@risklab/charts';

@Component({
  selector: 'uc-chart',
  standalone: true,
  template: '<div #chartHost style="width:100%;height:100%"></div>',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RiskLabChartComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() config!: ChartConfig;
  @Input() theme?: string | ThemeConfig;
  @Output() chartReady = new EventEmitter<AngularChartRef>();

  private chartRef?: AngularChartRef;
  private resizeObserver?: ResizeObserver;

  constructor(private el: ElementRef<HTMLElement>) {}

  ngAfterViewInit(): void {
    this.mount();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.chartRef) return;
    if (changes['config']) {
      this.chartRef.update(this.config);
    }
    if (changes['theme'] && this.theme) {
      this.chartRef.setTheme(this.theme);
    }
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    this.chartRef?.destroy();
  }

  private mount(): void {
    const host = this.el.nativeElement;
    this.chartRef = createAngularChart(host, {
      ...this.config,
      ...(this.theme ? { theme: this.theme } : {}),
    });

    this.resizeObserver = new ResizeObserver(() => {
      this.chartRef?.engine?.resize();
    });
    this.resizeObserver.observe(host);

    this.chartReady.emit(this.chartRef);
  }
}

/** NgModule for legacy Angular apps (pre-standalone). */
@NgModule({
  imports: [RiskLabChartComponent],
  exports: [RiskLabChartComponent],
})
export class RiskLabModule {}
`.trim();
}

// ── Angular Service ───────────────────────────────────────────────────────────

/**
 * Returns TypeScript source for an injectable Angular service that manages
 * a registry of chart instances, useful for dashboard apps.
 */
export function getAngularServiceSource(): string {
  return `
import { Injectable, OnDestroy } from '@angular/core';
import type { AngularChartRef } from '@risklab/charts-angular';

@Injectable({ providedIn: 'root' })
export class RiskLabService implements OnDestroy {
  private registry = new Map<string, AngularChartRef>();

  register(id: string, ref: AngularChartRef): void {
    this.registry.set(id, ref);
  }

  get(id: string): AngularChartRef | undefined {
    return this.registry.get(id);
  }

  remove(id: string): void {
    this.registry.get(id)?.destroy();
    this.registry.delete(id);
  }

  exportAll(format: 'png' | 'svg' | 'csv' = 'png'): Promise<Array<{ id: string; data: Blob | string }>> {
    return Promise.all(
      [...this.registry.entries()].map(async ([id, ref]) => ({
        id,
        data: await ref.exportChart(format),
      }))
    );
  }

  ngOnDestroy(): void {
    for (const ref of this.registry.values()) ref.destroy();
    this.registry.clear();
  }
}
`.trim();
}
